### ISSUE TITLE
Encoding object with null field crashes

### ISSUE THREAD

**Issue by andreskask123** [Kemonozume/json_conv#1]
Encoding object which has null value for String someField, will crash.

To reproduce, please add this test to encode_test.dart:

`    test('simplePersonTest', () {

      final Person p = new Person()
                            ..name = null;
      final sample = conv.encode(p); // this line crashes: RangeError (index): Invalid value: Valid value range is empty: 1
      expect(sample, isNotNull);
    });`

**Comment by Kemonozume** [comment]
thanks for the bug report
